name: version

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

permissions:
  contents: write

jobs:
  version-check:
    name: version-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          # - build: macos
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          # - build: windows
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get hash
        uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6

      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - name: Check Version
        run: |
          echo "short version hash => ${{ steps.short-sha.outputs.sha }}"
          echo "get-latest-tag ${{ steps.get-latest-tag.outputs.tag }}"