name: biz-folder

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

permissions:
  contents: write

jobs:
  biz-folder:
    name: biz-folder
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: biz-folder
    strategy:
      matrix: # https://docs.github.com/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
          - build: macos
            os: macos-latest
          - build: windows
            os: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check env
        run: |
          pwd
          echo "build => ${{ matrix.build }}"
          echo "os => ${{ matrix.os }}"