name: ci-info

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    branches:
      - '*'

jobs:
  info_print:
    runs-on: ubuntu-latest
    steps:
      - name: print args
        run: |
          echo " CI ${CI}"
          echo " GITHUB_ACTIONS ${GITHUB_ACTIONS}"
          echo " GITHUB_ACTION ${GITHUB_ACTION}"
          echo " RUNNER_DEBUG ${RUNNER_DEBUG}"
          echo " RUNNER_OS ${RUNNER_OS}"
          echo " runner.os ${{ runner.os }}"
          echo " RUNNER_ARCH ${RUNNER_ARCH}"
          echo ""
          echo " GITHUB_JOB ${GITHUB_JOB}"
          echo " GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo " github.event_name ${{ github.event_name }}"
          echo " github.event.pusher.name ${{ github.event.pusher.name }}"
          echo " github.event.pusher.email ${{ github.event.pusher.email }}"
          echo " github.event.sender.name ${{ github.event.sender.name }}"
          echo " github.event.sender.email ${{ github.event.sender.email }}"
          echo ""
          echo " GITHUB_SHA ${GITHUB_SHA}"
          echo " GITHUB_REF_TYPE ${GITHUB_REF_TYPE}"
          echo " GITHUB_REF ${GITHUB_REF}"
          echo " github.ref ${{ github.ref }}"
          echo " GITHUB_REF_NAME ${GITHUB_REF_NAME}"
          echo " GITHUB_BASE_REF ${GITHUB_BASE_REF}"
          echo " github.base_ref ${{ github.base_ref }}"
          echo " GITHUB_HEAD_REF ${GITHUB_HEAD_REF}"
          echo " github.head_ref ${{ github.head_ref }}"
          echo ""
          echo " github.event.pull_request.title ${{ github.event.pull_request.title }}"
          echo " github.event.pull_request.state ${{ github.event.pull_request.state }}"
          echo " github.event.pull_request.merged ${{ github.event.pull_request.merged }}"
          echo " github.event.pull_request.base.sha main ${{ github.event.pull_request.base.sha || 'main' }}"
          echo " github.event.pull_request.head.sha github.ref ${{ github.event.pull_request.head.sha || github.ref }}"
          echo ""
          echo " GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo " GITHUB_REPOSITORY_OWNER ${GITHUB_REPOSITORY_OWNER}"

  if-merged-main:
    if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: print args
      run: |
        echo The PR was merged main
        echo " GITHUB_JOB ${GITHUB_JOB}"
        echo " GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
        echo " github.event_name ${{ github.event_name }}"
        echo ""
        echo "this PR GITHUB_REF ${GITHUB_REF}"
        echo "this PR github.ref ${{ github.ref }}"
        echo ""
        echo "this PR github.base_ref ${{ github.base_ref }}"
        echo "this PR github.head_ref ${{ github.head_ref }}"
        echo "this PR github.event.pull_request.base.sha main ${{ github.event.pull_request.base.sha || 'main' }}"
        echo "this PR github.event.pull_request.head.sha github.ref ${{ github.event.pull_request.head.sha || github.ref }}"