name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - main
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    branches:
      - main

permissions:
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml

  biz-folder:
    needs:
      - version
    name: biz-folder
    uses: ./.github/workflows/biz-folder.yml
    with:
      short_sha: ${{ needs.version.outputs.short_sha }}
      tag_name: ${{ needs.version.outputs.tag_name }}
      upload_artifact_name: biz-folder

  deploy-tag:
    needs:
      - version
      - biz-folder
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    with:
      short_sha: ${{ needs.version.outputs.tag_name }}
      download_artifact_name: biz-folder
      prerelease: true