name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
      - 'release-*'
      - 'hotfix-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    branches:
      - 'main'
      - 'release-*'
      - 'FE-*'
      - 'BF-*'
      - 'PU-*'
      - 'DOC-*'
      - 'hotfix-*'
  pull_request_target:
    paths-ignore:
      - '**/README.md'
    types:
      - closed
    branches:
      - 'releases/**'

permissions:
  contents: write
  discussions: write

jobs:
  info_print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " CI ${CI}"
          echo " GITHUB_ACTIONS ${GITHUB_ACTIONS}"
          echo " GITHUB_ACTION ${GITHUB_ACTION}"
          echo " RUNNER_DEBUG ${RUNNER_DEBUG}"
          echo " RUNNER_OS ${RUNNER_OS}"
          echo " runner.os ${{ runner.os }}"
          echo " RUNNER_ARCH ${RUNNER_ARCH}"
          echo ""
          echo " GITHUB_JOB ${GITHUB_JOB}"
          echo " GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo " github.event_name ${{ github.event_name }}"
          echo ""
          echo " GITHUB_SHA ${GITHUB_SHA}"
          echo " GITHUB_REF_TYPE ${GITHUB_REF_TYPE}"
          echo " GITHUB_REF ${GITHUB_REF}"
          echo " github.ref ${{ github.ref }}"
          echo " GITHUB_REF_NAME ${GITHUB_REF_NAME}"
          echo " GITHUB_BASE_REF ${GITHUB_BASE_REF}"
          echo " github.base_ref ${{ github.base_ref }}"
          echo " GITHUB_HEAD_REF ${GITHUB_HEAD_REF}"
          echo " github.head_ref ${{ github.head_ref }}"
          echo ""
          echo " github.event.pull_request.title ${{ github.event.pull_request.title }}"
          echo " github.event.pull_request.state ${{ github.event.pull_request.state }}"
          echo " github.event.pull_request.mergeable ${{ github.event.pull_request.mergeable }}"
          echo " github.event.pull_request.merged ${{ github.event.pull_request.merged }}"
          echo ""
          echo " GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo " GITHUB_REPOSITORY_OWNER ${GITHUB_REPOSITORY_OWNER}"


  if-merged-main:
    if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged main
        echo "this PR GITHUB_REF ${GITHUB_REF}"
        echo "this PR github.event_name ${{ github.event_name }}"
        echo "this PR github.ref ${{ github.ref }}"
        echo "this PR github.base_ref ${{ github.base_ref }}"
        echo "this PR github.head_ref ${{ github.head_ref }}"

  version:
    name: version
    uses: ./.github/workflows/version.yml
    secrets: inherit

  biz-folder:
    needs:
      - version
    name: biz-folder
    uses: ./.github/workflows/biz-folder.yml
    secrets: inherit
    with:
      short_sha: ${{ needs.version.outputs.short_sha }}
      upload_artifact_name: biz-folder
      tag_name: ${{ needs.version.outputs.tag_name }}

  tag-from-pr-main:
    needs:
      - version
      - biz-folder
    if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' }}
    uses: ./.github/workflows/tag-from-pr.yml
    secrets: inherit

  deploy-tag:
    needs:
      - version
      - biz-folder
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.tag_changes }}
      download_artifact_name: biz-folder