name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - 'main'
      - 'release-*'
      - 'FE-*'
      - 'BF-*'
      - 'PU-*'
      - 'DOC-*'
      - 'hotfix-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    branches:
      - 'main'
      - 'release-*'
      - 'DOC-*'
      - 'hotfix-*'

permissions:
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml
    secrets: inherit

  biz-folder:
    needs:
      - version
    name: biz-folder
    uses: ./.github/workflows/biz-folder.yml
    secrets: inherit
    with:
      short_sha: ${{ needs.version.outputs.short_sha }}
      upload_artifact_name: biz-folder
      tag_name: ${{ needs.version.outputs.tag_name }}

  if-merged-main:
    if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged main
        echo "this PR GITHUB_REF ${GITHUB_REF}"
        echo "this PR github.event_name ${{ github.event_name }}"
        echo "this PR github.ref ${{ github.ref }}"
        echo "this PR github.base_ref ${{ github.base_ref }}"
        echo "this PR github.head_ref ${{ github.head_ref }}"

  deploy-tag:
    needs:
      - version
      - biz-folder
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.tag_changes }}
      download_artifact_name: biz-folder