name: get-release

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    outputs:
      short_sha:
        description: 'version short hash of the commit size 8'
        value: ${{ jobs.version-check.outputs.short_sha }}
      id:
        description: 'version id'
        value: ${{ jobs.version-check.outputs.id }}
      tag_name:
        description: 'tag name, if not tag will null'
        value: ${{ jobs.version-check.outputs.tag_name }}
      html_url:
        description: 'upload html, if not tag will null'
        value: ${{ jobs.version-check.outputs.html_url }}
      upload_url:
        description: 'upload url, if not tag will null'
        value: ${{ jobs.version-check.outputs.upload_url }}

jobs:
  version-check:
    name: version-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          # - build: macos
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          # - build: windows
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu
    outputs:
      short_sha: ${{ steps.short-sha.outputs.sha }}
      id: ${{ steps.get_release.outputs.id }}
      tag_name: ${{ steps.get_release.outputs.tag_name }}
      html_url: ${{ steps.get_release.outputs.html_url }}
      upload_url: ${{ steps.get_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get hash
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8

      - name: get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check Version
        run: |
          echo "short version hash => ${{ steps.short-sha.outputs.sha }}"
          echo "get release id => ${{ steps.get_release.outputs.id }}"
          echo "get release tag_name => ${{ steps.get_release.outputs.tag_name }}"
          echo "get release html_url => ${{ steps.get_release.outputs.html_url }}"
          echo "get release upload_url => ${{ steps.get_release.outputs.upload_url }}"