name: tag-from-pr

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

jobs:
  tag-standard-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          fetch-depth: 0 # all history for all tags and branches

      - name: Configure committer
        run: |
          # git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.email ${{ github.event.sender.email }}
          # git config --local user.name "github-actions[bot]"
          git config --local user.name ${{ github.event.sender.name }}

      - name: create-standard-version
        uses: convention-change/action-standard-version@main
        with:
          release-by-ref: ${{ github.head_ref }}
          # dry-run: true

      - name: Push change and tag
        run: |
          git config --local --add safe.directory .
          git push --follow-tags origin ${{ github.ref }}

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   if: ${{ github.event.pull_request.merged == true }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
      #     tags: true