name: version

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

permissions:
  contents: write

jobs:
  version-check:
    name: version-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          # - build: macos
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          # - build: macos
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - name: Get version
        id: get_version
        run: |
          echo "version_branch=${{ github.ref/refs\/heads\// }}" >> $GIT_VERSION_BRANCH
          echo "version_tag=${{ github.ref/refs\/tags\// }}" >> $GET_VERSION_TAG

      - name: Check Version
        run: |
          echo "short version hash => ${{ steps.short-sha.outputs.sha }}"
          echo "GIT_VERSION_BRANCH ${{ env.version_branch }}"
          echo "GET_VERSION_TAG ${{ env.version_tag }}"